# ---------- Deployment ---------- #
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy: {}
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb
        imagePullPolicy: Never
        name: influxdb
        resources: {}
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influx-claim
status: {}

---

# ---------- Service ---------- #
apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb-svc
spec:
  ports:
  - name: 8086-8086
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
  type: ClusterIP
status:
  loadBalancer: {}

---

# ---------- Persistent Volume(Claim) ---------- #
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi