apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy: {}
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana
        name: grafana
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: influx-secret
        - secretRef:
            name: grafana-secret
        env:
        - name: HOSTNAME
          value: http://grafana-svc:3000
        resources: {}
status: {}

---

apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: admin
    GF_SECURITY_ADMIN_PASSWORD: pass
    GF_SERVER_DOMAIN: grafana-svc
    GF_SERVER_HTTP_PORT: "3000"
    GF_SERVER_PROTOCOL: http
    GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /usr/share/grafana/conf/provisioning/dashboards/mine/overview.json

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana
  name: grafana-svc
spec:
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
status:
  loadBalancer: {}
