# ---------- Service ---------- #
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-svc
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    app: nginx
  type: LoadBalancer
status:
  loadBalancer: {}

---

# ---------- Deployment ---------- #
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: ssh-secret
        resources: {}
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - /tmp/liveness.sh
          initialDelaySeconds: 10
          periodSeconds: 5
status: {}

---

apiVersion: v1
kind: Secret
metadata:
  name: ssh-secret
type: Opaque
stringData:
  SSH_USERNAME: user
  SSH_PASSWORD: pass