# ---------- Service ---------- #
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    targetPort: 5000

---

# ---------- Deployment ---------- #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: mysql-secret
        ports:
        - containerPort: 5000
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - /tmp/liveness.sh
          initialDelaySeconds: 10
          periodSeconds: 5