# ---------- Service ---------- #
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/address-pool: pma-ip
  labels:
    app: phpmyadmin-deployment
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin-deployment
  ports:
  - port: 5000
    targetPort: 5000

---

# ---------- Deployment ---------- #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-deployment
  template:
    metadata:
      labels:
        app: phpmyadmin-deployment
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: mysql-svc
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: phpmyadmin-persistent-storage
          mountPath: /var/www/localhost/htdocs
      volumes:
      - name: phpmyadmin-persistent-storage
        persistentVolumeClaim:
          claimName: phpmyadmin-pv-claim

---

# ---------- Persistent Volume Claim ---------- #
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin-pv-claim
  labels:
    app: phpmyadmin-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi