apiVersion: v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-svc
  name: nginx-svc
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-svc
  type: LoadBalancer
status:
  loadBalancer: {}
