# ---------- Deployment ---------- #
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ftps
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps-alpine
        name: ftps-alpine
        imagePullPolicy: Never
        resources: {}
status: {}

---

# ---------- Service ---------- #
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ftps
  name: ftps
spec:
  ports:
    - name: command-ctrl
      port: 20
      targetPort: 20
    - name: data-transfer
      port: 21
      targetPort: 21
    - name: pasv-port
      port: 30000
      targetPort: 31000
  selector:
    app: ftps
  type: LoadBalancer
status:
  loadBalancer: {}